### PR TITLE
Sqlite of cityhunter

### PR DESCRIPTION
**Pull request by NguyenVanTienIT**
marge code sqlite

### CODE REVIEW

**Comment by Hanv2itedu** [comment]
Good job, you did a lot, but our codes need a little of comment lines and follow the code convention. Please change your code to professional. Thank u.

**Comment by NguyenVanTienIT** [comment]
oh no , what do you say ? . Can you speak vietnamese ??? :)))))

**Comment by NguyenVanTienIT** [comment]
How many have it error ??? :)))

**Comment by Hanv2itedu** [comment]
cần comment thêm cho code với lại chỉnh code theo convention nha

**Comment by Hanv2itedu** [comment]
ok

**Pull request merged**
